### PR TITLE
Port to Godot 3

### PR DESCRIPTION
**Pull request by Beracosa**
I was using your addon but needed it for Godot 3, so I ported it over. Here's my pr if you would like to merge. Or maybe you'd like to create a new branch as a separate version. Anyways, everything should work for Godot 3 if anyone comes across this.

### CODE REVIEW

**Comment by blurymind** [comment]
Hi, wonderful stuff.  Thank you for porting it over :) 

Would you mind moving the old one to its own subfolder and have them like this:
```
addons/1dollar-godot2.1
addons/1dollar-godot3.0
```

That way we have them both on one repository

**Comment by blurymind** [comment]
actually scratch that, I just moved the old one to 2.1 branch

**Comment by blurymind** [comment]
merged :tada: thank you for the contribution

**Comment by ficasmica** [comment]
> I was using your addon but needed it for Godot 3, so I ported it over. Here's my pr if you would like to merge. Or maybe you'd like to create a new branch as a separate version. Anyways, everything should work for Godot 3 if anyone comes across this.

Hey, is it possible to use this addon now for godot 3.2.3? I tried to import it but it says there is an error in the syntax. Any advice?

**Comment by Beracosa** [comment]
It doesn't seem to work like the readme says just by moving all the files(not sure if this is a Godot or addon problem).

However, this worked for me on 3.2.3:

1. Create the 'addons' and '1dollar' folder through Godot's UI nested like below.
```
res://
    addons
        1dollar
```
2. Unzip the archive.
3. Drag the 3 png's from the unzipped 1dollar folder to the newly created 1dollar folder through Godot's UI.
4. Right click the 1dollar folder in Godot and click open in file manager.
5. Move the rest of the files to the 1dollar folder through the file manager.

**Comment by ficasmica** [comment]
> It doesn't seem to work like the readme says just by moving all the files(not sure if this is a Godot or addon problem).
> 
> However, this worked for me on 3.2.3:
> 
> 1. Create the 'addons' and '1dollar' folder through Godot's UI nested like below.
> 
> ```
> res://
>     addons
>         1dollar
> ```
> 
> 1. Unzip the archive.
> 2. Drag the 3 png's from the unzipped 1dollar folder to the newly created 1dollar folder through Godot's UI.
> 3. Right click the 1dollar folder in Godot and click open in file manager.
> 4. Move the rest of the files to the 1dollar folder through the file manager.

You made my day sir, thank you very much :)

**Comment by blurymind** [comment]
thanks. i need to update the readme

**Pull request merged**
